repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.7
    hooks:
      - id: check-model-has-description
        files: ^airflow_lappis/dags/dbt/(ipea|mir)/models/.*\.(sql|ya?ml)$
      - id: check-model-columns-have-desc
        files: ^airflow_lappis/dags/dbt/(ipea|mir)/models/.*\.(sql|ya?ml)$
      - id: check-source-table-has-description
        files: ^airflow_lappis/dags/dbt/(ipea|mir)/models/.*\.ya?ml$
      - id: check-source-columns-have-desc
        files: ^airflow_lappis/dags/dbt/(ipea|mir)/models/.*\.ya?ml$
