name: 'ipea'

version: 1.0.0
config-version: 2

profile: ipea

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ipea: 
    +database: analytics
    metadata:
      +materialized: incremental
      +schema: metadata
    contratos_dbt:
      +materialized: table
      +schema: contratos
      bronze:
        +materialized: incremental
        +grants:
          select: []
      silver:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      gold:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      views:
        +materialized: view
    pessoas_dbt:
      +materialized: table
      +schema: pessoas
      bronze:
        +grants:
          select: []
      silver:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      gold:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      views:
        +materialized: view
    ted_dbt:
      +materialized: table
      +schema: ted
      bronze:
        +grants:
          select: []
      silver:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      gold:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      views:
        +materialized: view
    orcamento_dbt:
      +materialized: table
      +schema: orcamento
      bronze:
        +grants:
          select: []
      silver:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      views:
        +materialized: view
    sistema_sisbolsas:
      +materialized: table
      +schema: sistema_sisbolsas
      bronze:
        +materialized: table
        +grants:
          select: []
      silver:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
      gold:
        +grants:
          select: ["{{ env_var('DB_DW_READONLY_ROLE', 'de_postgres') }}"]
    # siape_dbt: 
    #   +materialized: table 
    #   +schema: siape 
    #   views:
    #     +materialized: view


on-run-start:
  - '{{create_udfs()}}'
  - '{{conceder_usage_dinamico()}}'